# Generated by Django 4.2 on 2024-08-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_class',
            field=models.CharField(choices=[('seater', 'Seater'), ('semi-sleeper', 'Semi-Sleeper'), ('sleeper', 'Sleeper')], default='seater', max_length=20),
        ),
    ]
